### ISSUE TITLE
Unrecognized raster type

### ISSUE THREAD

**Issue by snowman2** [ContinuumIO/whitebox-geospatial-analysis-tools#11]
After downloading the elevation file with quest and running BreachDepression, I see this message:
![image](https://user-images.githubusercontent.com/8699967/30289016-59d29a1e-96f0-11e7-86a4-16a25cd5ed55.png)

**Comment by dharhas** [comment]
Is this with the notebook I attached. Because that notebook worked on my laptop and Jim's on Thursday. If that notebook doesn't run then it is an install/environment issue. If it does then we need to compare differences.

**Comment by snowman2** [comment]
@dharhas, I used the notebook in this PR https://github.com/ContinuumIO/EarthSim/pull/90.
The fork is located here: https://github.com/snowman2/EarthSim/tree/gssha

**Comment by snowman2** [comment]
@dharhas, can you try the notebook WorkflowGSSHA.ipynb and see if you can get it to work?

**Comment by dharhas** [comment]
To narrow things down @snowman2 Can you check if the first part of the attached notebook (i.e. until breachdepressions) works for you.

**Comment by dharhas** [comment]
ok it won't let me attach a notebook...

**Comment by dharhas** [comment]
@snowman2 

I think I got it. It is a difference in our download_data scripts. My notebook always merges and clips the data to a bbox. This has the side effect of converting the raster to a geotiff file. Your download_data function only merges if more than one tile is downloaded.

Whitebox has limited raster support since it doesn't depend on gdal, so it doesn't support the original .img format that is downloaded and hence fails.

**Comment by snowman2** [comment]
@dharhas, thanks! I updated the download script to match your behavior so the file is always a tiff as it will be clipped.
